version: 0.2

phases:
  install:
    on-failure: ABORT
  pre_build:
      on-failure: ABORT
    commands:
      - echo 'Logging in to Amazon ECR ...'
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY
  build:
      on-failure: ABORT
    commands:
      - echo 'Building Docker image ...'
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
  post_build:
      on-failure: ABORT
    commands:
      - docker images ls -a
      - echo 'Pushing Docker image to ECR ...'
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG
      - echo 'Updating ECS service ...'
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
